// GENERATED FILE - DO NOT EDIT.
// Source: packages/design-tokens/tokens.json
// Regenerate: node tools/design/generate-tokens.mjs

/** Every CSS custom property the Aurelia design system defines. */
export const CSS_VARIABLE_NAMES = [
  '--aurelia-color-accent',
  '--aurelia-color-accent-subtle',
  '--aurelia-color-accent-text',
  '--aurelia-color-background',
  '--aurelia-color-background-elevated',
  '--aurelia-color-border',
  '--aurelia-color-command-palette-background',
  '--aurelia-color-command-palette-border',
  '--aurelia-color-command-palette-highlight',
  '--aurelia-color-command-palette-text',
  '--aurelia-color-command-palette-text-muted',
  '--aurelia-color-danger',
  '--aurelia-color-new-tab-background',
  '--aurelia-color-new-tab-card-background',
  '--aurelia-color-omnibox-background',
  '--aurelia-color-omnibox-background-hover',
  '--aurelia-color-omnibox-border',
  '--aurelia-color-omnibox-text',
  '--aurelia-color-omnibox-text-muted',
  '--aurelia-color-success',
  '--aurelia-color-surface',
  '--aurelia-color-surface-glass',
  '--aurelia-color-surface-glass-border',
  '--aurelia-color-tab-background-active',
  '--aurelia-color-tab-background-hover',
  '--aurelia-color-tab-background-inactive',
  '--aurelia-color-tab-border',
  '--aurelia-color-tab-text-active',
  '--aurelia-color-tab-text-inactive',
  '--aurelia-color-text',
  '--aurelia-color-text-muted',
  '--aurelia-color-toolbar-background',
  '--aurelia-color-toolbar-background-opaque',
  '--aurelia-color-warning',
  '--aurelia-effect-blur',
  '--aurelia-effect-blur-strong',
  '--aurelia-effect-focus-ring-offset',
  '--aurelia-effect-focus-ring-width',
  '--aurelia-effect-shadow-lg',
  '--aurelia-effect-shadow-md',
  '--aurelia-effect-shadow-sm',
  '--aurelia-motion-duration-fast',
  '--aurelia-motion-duration-normal',
  '--aurelia-motion-duration-slow',
  '--aurelia-motion-easing-ease-out',
  '--aurelia-motion-easing-standard',
  '--aurelia-radius-lg',
  '--aurelia-radius-md',
  '--aurelia-radius-pill',
  '--aurelia-radius-sm',
  '--aurelia-radius-tab',
  '--aurelia-radius-tab-active',
  '--aurelia-radius-xl',
  '--aurelia-radius-xs',
  '--aurelia-space-lg',
  '--aurelia-space-md',
  '--aurelia-space-sm',
  '--aurelia-space-xl',
  '--aurelia-space-xs',
  '--aurelia-space-xxl',
  '--aurelia-space-xxs',
  '--aurelia-space-xxxl',
  '--aurelia-type-family',
  '--aurelia-type-family-monospace',
  '--aurelia-type-size-base',
  '--aurelia-type-size-display',
  '--aurelia-type-size-lg',
  '--aurelia-type-size-sm',
  '--aurelia-type-size-title',
  '--aurelia-type-size-xl',
  '--aurelia-type-size-xs',
  '--aurelia-type-weight-medium',
  '--aurelia-type-weight-regular',
  '--aurelia-type-weight-semibold',
  '--aurelia-z-index-command-palette',
  '--aurelia-z-index-dropdown',
  '--aurelia-z-index-modal',
  '--aurelia-z-index-toast',
] as const;

/** Shared (theme-independent) token values. */
export const SHARED_TOKENS = {
  '--aurelia-color-accent': "#6e7bf2",
  '--aurelia-color-tab-border': "rgba(20, 22, 28, 0.10)",
  '--aurelia-radius-xs': "4px",
  '--aurelia-radius-sm': "6px",
  '--aurelia-radius-md': "10px",
  '--aurelia-radius-lg': "16px",
  '--aurelia-radius-xl': "24px",
  '--aurelia-radius-pill': "999px",
  '--aurelia-radius-tab': "10px 10px 0 0",
  '--aurelia-radius-tab-active': "10px 10px 0 0",
  '--aurelia-space-xxs': "2px",
  '--aurelia-space-xs': "4px",
  '--aurelia-space-sm': "8px",
  '--aurelia-space-md': "12px",
  '--aurelia-space-lg': "16px",
  '--aurelia-space-xl': "24px",
  '--aurelia-space-xxl': "32px",
  '--aurelia-space-xxxl': "48px",
  '--aurelia-type-family': "\"Segoe UI Variable Text\", \"Segoe UI\", system-ui, -apple-system, \"SF Pro Text\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
  '--aurelia-type-family-monospace': "\"Cascadia Mono\", \"SFMono-Regular\", ui-monospace, Consolas, \"Liberation Mono\", monospace",
  '--aurelia-type-size-xs': "11px",
  '--aurelia-type-size-sm': "12px",
  '--aurelia-type-size-base': "13px",
  '--aurelia-type-size-lg': "15px",
  '--aurelia-type-size-xl': "18px",
  '--aurelia-type-size-title': "22px",
  '--aurelia-type-size-display': "32px",
  '--aurelia-type-weight-regular': "400",
  '--aurelia-type-weight-medium': "500",
  '--aurelia-type-weight-semibold': "600",
  '--aurelia-motion-duration-fast': "120ms",
  '--aurelia-motion-duration-normal': "180ms",
  '--aurelia-motion-duration-slow': "240ms",
  '--aurelia-motion-easing-standard': "cubic-bezier(0.2, 0, 0, 1)",
  '--aurelia-motion-easing-ease-out': "cubic-bezier(0, 0, 0.2, 1)",
  '--aurelia-effect-blur': "12px",
  '--aurelia-effect-blur-strong': "20px",
  '--aurelia-effect-shadow-sm': "0 1px 2px rgba(20, 22, 28, 0.10)",
  '--aurelia-effect-shadow-md': "0 4px 12px rgba(20, 22, 28, 0.15)",
  '--aurelia-effect-shadow-lg': "0 8px 24px rgba(20, 22, 28, 0.20)",
  '--aurelia-effect-focus-ring-width': "2px",
  '--aurelia-effect-focus-ring-offset': "2px",
  '--aurelia-z-index-command-palette': "1000",
  '--aurelia-z-index-dropdown': "500",
  '--aurelia-z-index-modal': "1000",
  '--aurelia-z-index-toast': "1100",
} as const;

/** Light-theme token values. */
export const LIGHT_TOKENS = {
  '--aurelia-color-accent-text': "#ffffff",
  '--aurelia-color-accent-subtle': "rgba(79, 91, 213, 0.10)",
  '--aurelia-color-background': "#f6f7fb",
  '--aurelia-color-background-elevated': "#ffffff",
  '--aurelia-color-surface': "#ffffff",
  '--aurelia-color-surface-glass': "rgba(255, 255, 255, 0.72)",
  '--aurelia-color-surface-glass-border': "rgba(255, 255, 255, 0.30)",
  '--aurelia-color-omnibox-background': "#ffffff",
  '--aurelia-color-omnibox-background-hover': "#f0f2f7",
  '--aurelia-color-omnibox-border': "rgba(20, 22, 28, 0.10)",
  '--aurelia-color-omnibox-text': "#14161c",
  '--aurelia-color-omnibox-text-muted': "#8a90a2",
  '--aurelia-color-tab-background-inactive': "rgba(20, 22, 28, 0.03)",
  '--aurelia-color-tab-background-active': "#ffffff",
  '--aurelia-color-tab-background-hover': "rgba(20, 22, 28, 0.05)",
  '--aurelia-color-tab-text-inactive': "#5a6072",
  '--aurelia-color-tab-text-active': "#14161c",
  '--aurelia-color-toolbar-background': "rgba(255, 255, 255, 0.80)",
  '--aurelia-color-toolbar-background-opaque': "#ffffff",
  '--aurelia-color-command-palette-background': "#ffffff",
  '--aurelia-color-command-palette-border': "rgba(20, 22, 28, 0.12)",
  '--aurelia-color-command-palette-text': "#14161c",
  '--aurelia-color-command-palette-text-muted': "#8a90a2",
  '--aurelia-color-command-palette-highlight': "rgba(110, 123, 242, 0.12)",
  '--aurelia-color-new-tab-background': "#f6f7fb",
  '--aurelia-color-new-tab-card-background': "#ffffff",
  '--aurelia-color-text': "#14161c",
  '--aurelia-color-text-muted': "#5a6072",
  '--aurelia-color-border': "rgba(20, 22, 28, 0.12)",
  '--aurelia-color-success': "#1c7a4d",
  '--aurelia-color-warning': "#8a5a00",
  '--aurelia-color-danger': "#b3261e",
} as const;

/** Dark-theme token values. */
export const DARK_TOKENS = {
  '--aurelia-color-accent-text': "#0b0d12",
  '--aurelia-color-accent-subtle': "rgba(139, 149, 255, 0.16)",
  '--aurelia-color-background': "#0e1015",
  '--aurelia-color-background-elevated': "#161922",
  '--aurelia-color-surface': "#161922",
  '--aurelia-color-surface-glass': "rgba(22, 25, 34, 0.66)",
  '--aurelia-color-surface-glass-border': "rgba(255, 255, 255, 0.10)",
  '--aurelia-color-omnibox-background': "#1e2028",
  '--aurelia-color-omnibox-background-hover': "#252830",
  '--aurelia-color-omnibox-border': "rgba(238, 240, 246, 0.10)",
  '--aurelia-color-omnibox-text': "#eef0f6",
  '--aurelia-color-omnibox-text-muted': "#7a8090",
  '--aurelia-color-tab-background-inactive': "rgba(238, 240, 246, 0.04)",
  '--aurelia-color-tab-background-active': "#1e2028",
  '--aurelia-color-tab-background-hover': "rgba(238, 240, 246, 0.06)",
  '--aurelia-color-tab-text-inactive': "#a3a9bb",
  '--aurelia-color-tab-text-active': "#eef0f6",
  '--aurelia-color-toolbar-background': "rgba(22, 25, 34, 0.80)",
  '--aurelia-color-toolbar-background-opaque': "#161922",
  '--aurelia-color-command-palette-background': "#1e2028",
  '--aurelia-color-command-palette-border': "rgba(238, 240, 246, 0.12)",
  '--aurelia-color-command-palette-text': "#eef0f6",
  '--aurelia-color-command-palette-text-muted': "#7a8090",
  '--aurelia-color-command-palette-highlight': "rgba(139, 149, 255, 0.16)",
  '--aurelia-color-new-tab-background': "#0e1015",
  '--aurelia-color-new-tab-card-background': "#161922",
  '--aurelia-color-text': "#eef0f6",
  '--aurelia-color-text-muted': "#a3a9bb",
  '--aurelia-color-border': "rgba(238, 240, 246, 0.14)",
  '--aurelia-color-success': "#5fd39a",
  '--aurelia-color-warning': "#f0c05a",
  '--aurelia-color-danger': "#ff8a80",
} as const;

export type AureliaCssVariableName = (typeof CSS_VARIABLE_NAMES)[number];
