/**
 * The constrained-checkout reductions of tools/chromium/sync.mjs.
 *
 * HOSTED_CONSTRAINED_EXPERIMENT needs a checkout that fetches less, and the
 * honest way to do that is to use switches upstream documents rather than
 * inventing any: `target_os` and `custom_vars` come straight from gclient's
 * own file format and from Chromium's DEPS, and `--no-history` is documented
 * at the pinned revision. These tests pin three things:
 *
 *   1. an ordinary checkout is unchanged (default .gclient is byte-identical
 *      to what it always was);
 *   2. each reduction is emitted only when it was asked for;
 *   3. `--no-history` is only passed when the installed gclient advertises
 *      it, because an unknown option fails the sync before it starts.
 */
import { describe, expect, it } from 'vitest';

import {
  NO_HISTORY_FLAG,
  gclientFileText,
  resolveSyncArgs,
} from '../../tools/chromium/sync.mjs';

describe('gclient file generation', () => {
  it('writes the plain solution when nothing is reduced', () => {
    const text = gclientFileText();
    expect(text).toBe(
      [
        '# Aurelia Browser - generated by tools/chromium/sync.mjs.',
        '# Do not edit by hand; the pinned revision is managed by the tooling.',
        'solutions = [',
        '  {',
        '    "name": "src",',
        '    "url": "https://chromium.googlesource.com/chromium/src.git",',
        '    "managed": False,',
        '    "custom_deps": {},',
        '    "custom_vars": {},',
        '  },',
        ']',
        '',
      ].join('\n'),
    );
    expect(text).not.toContain('target_os');
    expect(text).not.toContain('checkout_configuration');
  });

  it('adds target_os only when a target operating system list is given', () => {
    const text = gclientFileText({ targetOs: ['win'] });
    expect(text).toContain('"target_os": ["win"],');
    expect(text).toContain(
      'https://chromium.googlesource.com/chromium/src.git',
    );
    expect(gclientFileText({ targetOs: [] })).not.toContain('target_os');
  });

  it('adds DEPS\' own "small" checkout configuration on request', () => {
    const text = gclientFileText({ smallCheckout: true });
    expect(text).toContain(
      '"custom_vars": { "checkout_configuration": "small" },',
    );
  });

  it('keeps both reductions independent', () => {
    const text = gclientFileText({ targetOs: ['win'], smallCheckout: true });
    expect(text).toContain(
      '"custom_vars": { "checkout_configuration": "small" },',
    );
    expect(text).toContain('"target_os": ["win"],');
  });
});

describe('gclient sync argument resolution', () => {
  it('always pins the revision', () => {
    expect(resolveSyncArgs({ revision: 'a'.repeat(40) })).toEqual([
      'sync',
      '--revision',
      `src@${'a'.repeat(40)}`,
    ]);
  });

  it('refuses to run without a revision', () => {
    expect(() => resolveSyncArgs({})).toThrow(/requires a pinned revision/);
  });

  it('adds branch heads and tags only with --with-refs', () => {
    const args = resolveSyncArgs({ revision: 'abc', withRefs: true });
    expect(args).toContain('--with_branch_heads');
    expect(args).toContain('--with_tags');
  });

  it('passes --no-history only when gclient advertises it', () => {
    expect(
      resolveSyncArgs({
        revision: 'abc',
        noHistory: true,
        supportsNoHistory: true,
      }),
    ).toContain(NO_HISTORY_FLAG);
    // Asking is not enough: an unknown option would fail the sync outright.
    expect(
      resolveSyncArgs({
        revision: 'abc',
        noHistory: true,
        supportsNoHistory: false,
      }),
    ).not.toContain(NO_HISTORY_FLAG);
    expect(
      resolveSyncArgs({ revision: 'abc', supportsNoHistory: true }),
    ).not.toContain(NO_HISTORY_FLAG);
  });

  it('separates the sources from the DEPS hooks only when asked', () => {
    // On a hosted runner the hooks are the fragile part: one of them
    // downloads the pinned Visual Studio toolchain and Windows SDK, and its
    // failure used to take the whole hour-long sync down with it.
    expect(resolveSyncArgs({ revision: 'abc' })).not.toContain('--nohooks');
    expect(resolveSyncArgs({ revision: 'abc', noHooks: true })).toContain(
      '--nohooks',
    );
    expect(
      resolveSyncArgs({ revision: 'abc', noHooks: true }).slice(0, 3),
    ).toEqual(['sync', '--revision', 'src@abc']);
  });

  it('never drops the revision pin to make the sync smaller', () => {
    const args = resolveSyncArgs({
      revision: 'deadbeef',
      withRefs: true,
      noHistory: true,
      supportsNoHistory: true,
    });
    expect(args.slice(0, 3)).toEqual(['sync', '--revision', 'src@deadbeef']);
  });
});
