# Copyright 2026 The Aurelia Authors
# Use of this source code is governed by the Mozilla Public License, v. 2.0,
# that can be found in the LICENSE file at the repository root.
## Aurelia Browser - resources for chrome://aurelia.
# The build_webui() template generates:
#   chrome/grit/aurelia_resources.h
#   chrome/grit/aurelia_resources_map.h
#   aurelia_resources.pak
# and compiles the TypeScript below with Chromium's own toolchain. No Node.js
# toolchain is required at build time; Node is only used by development
# tooling that generates checked-in files (see tools/design and
# tools/chromium/cli.mjs).
import("//ui/webui/resources/tools/build_webui.gni")
assert(!is_android)
build_webui("build") {
  grd_prefix = "aurelia"
  static_files = [ "aurelia.html" ]
  css_files = [
    "aurelia.css",
    "design_tokens.css",
  ]
  ts_files = [
    "aurelia_app.ts",
    "aurelia_status_card.ts",
    "command_palette.ts",
  ]
  ts_deps = [ "//ui/webui/resources/js:build_ts" ]
  webui_context_type = "trusted"
}
