#!/usr/bin/env node
/**
 * Windows `git.bat` compatibility shim for depot_tools.
 *
 * ## The failure this module exists for
 *
 * Run
 * https://github.com/ankworks/aurelia/actions/runs/38043815539 failed with:
 *
 *   FileNotFoundError: [WinError 2] The system cannot find the file specified.
 *     depot_tools/git_cache.py, Mirror.GetCachePath()
 *
 * Three upstream facts combine:
 *
 * 1. `depot_tools/git_cache.py` hard-codes the git program name for Windows:
 *
 *        git_exe = "git.bat" if sys.platform.startswith("win") else "git"
 *
 * 2. `Mirror.GetCachePath()` shells out with
 *    `subprocess.check_output([cls.git_exe, "config", ...,
 *    "--type", "path", "cache.cachepath"])` and catches **only**
 *    `subprocess.CalledProcessError`. A missing executable raises
 *    `FileNotFoundError` (an `OSError`), which is not caught, so it escapes.
 *
 * 3. `gclient_scm.GitWrapper.cache_dir` calls `Mirror.GetCachePath()` for every
 *    git dependency in every `gclient sync` - not only when a cache directory
 *    is configured - and catches **only** `RuntimeError` (the "cache not
 *    configured" case). So the missing `git.bat` aborts the whole sync before
 *    the first fetch, whether or not the git cache is wanted.
 *
 * Neither side ships the file. depot_tools has no `git.bat` in its tree (it
 * stopped vendoring Git for Windows years ago but kept the hard-coded name),
 * and Git for Windows - which is what GitHub-hosted Windows runners install
 * under `C:\Program Files\Git` - ships `git.exe` in `cmd\` and `bin\` and no
 * `git.bat` anywhere. `CreateProcess` therefore fails with `WinError 2`.
 *
 * ## The fix
 *
 * Provide the missing executable. This module writes a `git.bat` shim into the
 * Chromium destination (never into depot_tools, never into a system
 * directory, never onto the machine-wide PATH) that forwards every argument to
 * the real `git.exe` and returns its exit code verbatim. The shim directory is
 * prepended to the PATH of the `gclient` child process only.
 *
 * That keeps the git cache enabled: `Mirror.GetCachePath()` now reaches its
 * `git config cache.cachepath` probe, gets a real `CalledProcessError` when the
 * key is unset (instead of `FileNotFoundError`), and falls back to
 * `$GIT_CACHE_PATH` and then to `RuntimeError`, which `GitWrapper.cache_dir`
 * handles. If a cache directory is configured later, it is used as before.
 *
 * ## Also exported
 *
 * The lookup and reporting helpers are pure enough to be unit-tested on a
 * Linux runner, which is the only place this suite runs. See
 * `tests/tools/windows-git.test.mjs`.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/** The executable name depot_tools' git_cache.py expects on Windows. */
export const GIT_BAT_NAME = 'git.bat';

/** Directory inside the Chromium destination that holds the generated shim. */
export const GIT_SHIM_DIR_NAME = '.aurelia-git-shim';

/**
 * Git for Windows install locations, used when `where.exe` is unavailable.
 * `cmd\git.exe` is the wrapper Git for Windows documents for non-MSYS callers.
 */
export const KNOWN_WINDOWS_GIT_EXECUTABLES = Object.freeze([
  'C:\\Program Files\\Git\\cmd\\git.exe',
  'C:\\Program Files\\Git\\bin\\git.exe',
]);

/** Directory holding the shim for a Chromium destination. */
export function gitShimDirectory(dest) {
  return path.join(dest, GIT_SHIM_DIR_NAME);
}

/**
 * The generated batch file. CRLF line endings because cmd.exe is happier with
 * them, and `exit /b %ERRORLEVEL%` so `subprocess.check_output` sees git's own
 * exit status (a non-zero status is meaningful: git_cache.py relies on
 * `CalledProcessError` to detect an unset `cache.cachepath`).
 */
export function gitBatContents(gitExecutable) {
  const lines = [
    '@echo off',
    'rem Generated by tools/chromium/lib/windows-git.mjs - do not edit by hand.',
    'rem',
    'rem depot_tools git_cache.py hard-codes Mirror.git_exe = "git.bat" on',
    'rem Windows and shells out to it with subprocess.check_output, catching',
    'rem only CalledProcessError. Git for Windows ships git.exe and no git.bat,',
    'rem so the lookup failed with FileNotFoundError [WinError 2] in',
    'rem Mirror.GetCachePath() and aborted gclient sync before any fetch.',
    'rem This shim is the missing executable: forward everything to git.exe and',
    'rem return its exit code unchanged.',
    `"${gitExecutable}" %*`,
    'exit /b %ERRORLEVEL%',
  ];
  return `${lines.join('\r\n')}\r\n`;
}

/**
 * The PATH of an environment, read case-insensitively.
 *
 * Windows environment variable names are case-insensitive and Actions runners
 * spell it `Path`, so a plain `env.PATH` lookup is only reliable on POSIX (or
 * through Node's own case-insensitive `process.env` proxy, which a plain
 * object copy of it does not have).
 */
export function pathEntries(env = {}, platform = process.platform) {
  const key = Object.keys(env).find(
    (candidate) => candidate.toUpperCase() === 'PATH',
  );
  if (key === undefined || typeof env[key] !== 'string') {
    return [];
  }
  const delimiter = platform === 'win32' ? ';' : path.delimiter;
  return env[key].split(delimiter).filter((entry) => entry.length > 0);
}

/**
 * Resolve a file name the way Windows `CreateProcess` does when the name
 * already carries an extension: the name is used verbatim, `PATHEXT` is not
 * consulted, and each PATH entry is tried in order.
 *
 * @returns {string|null} the PATH entry that contains `name`, or null.
 */
export function resolvesInPathEntries(
  name,
  entries,
  { exists = existsSync, separator = path.sep } = {},
) {
  for (const entry of entries) {
    const candidate = joinPathEntry(entry, name, separator);
    try {
      if (exists(candidate)) {
        return candidate;
      }
    } catch {
      // An unreadable or malformed PATH entry is skipped, not fatal.
    }
  }
  return null;
}

/** Join a PATH entry and a file name with the platform's own separator. */
function joinPathEntry(entry, name, separator) {
  if (/[\\/]$/.test(entry)) {
    return `${entry}${name}`;
  }
  return `${entry}${separator}${name}`;
}

/**
 * `where.exe <name>` output as a list of absolute paths, empty when the lookup
 * failed or `where.exe` is not available.
 */
export function whereExecutable(name, { env = process.env, spawn = spawnSync } = {}) {
  const result = spawn('where.exe', [name], {
    encoding: 'utf8',
    env,
    windowsHide: true,
  });
  if (result.error !== undefined || result.status !== 0) {
    return [];
  }
  return String(result.stdout ?? '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

/** First line of `<file> --version`, or null when the file cannot be run. */
export function executableVersion(file, { env = process.env, spawn = spawnSync } = {}) {
  const result = spawn(file, ['--version'], {
    encoding: 'utf8',
    env,
    windowsHide: true,
  });
  if (result.error !== undefined || result.status !== 0) {
    return null;
  }
  const text = `${result.stdout ?? ''}${result.stderr ?? ''}`.trim();
  if (text.length === 0) {
    return 'present';
  }
  return text.split('\n')[0].trim();
}

/** Candidate git executables on Windows, most specific first. */
export function windowsGitCandidates({
  env = process.env,
  spawn = spawnSync,
  exists = existsSync,
} = {}) {
  const candidates = [
    ...whereExecutable('git.exe', { env, spawn }),
    ...KNOWN_WINDOWS_GIT_EXECUTABLES,
  ];
  const seen = new Set();
  return candidates.filter((candidate) => {
    const normalized = candidate.toLowerCase();
    if (seen.has(normalized) || !exists(candidate)) {
      return false;
    }
    seen.add(normalized);
    return true;
  });
}

/**
 * Find a working git and report where it came from.
 *
 * @returns {{path: string, version: string, source: string}|null}
 */
export function resolveGitExecutable({
  env = process.env,
  platform = process.platform,
  spawn = spawnSync,
  exists = existsSync,
} = {}) {
  const candidates =
    platform === 'win32'
      ? windowsGitCandidates({ env, spawn, exists })
      : ['git'];
  for (const candidate of candidates) {
    const version = executableVersion(candidate, { env, spawn });
    if (version !== null) {
      return { path: candidate, version, source: 'PATH' };
    }
  }
  return null;
}

/**
 * Create the `git.bat` shim for the gclient child environment.
 *
 * A no-op that returns `null` everywhere except Windows, because nowhere else
 * does depot_tools ask for `git.bat`.
 *
 * @returns {{directory: string, gitBat: string, gitExecutable: string,
 *   version: string, alreadyResolvable: boolean}|null}
 */
export function ensureWindowsGitShim({
  dest,
  env = process.env,
  platform = process.platform,
  log = () => {},
  spawn = spawnSync,
  exists = existsSync,
} = {}) {
  if (platform !== 'win32') {
    return null;
  }
  const entries = pathEntries(env, platform);
  const alreadyResolvable =
    resolvesInPathEntries(GIT_BAT_NAME, entries, { exists }) !== null;
  log(
    alreadyResolvable
      ? `git.bat: already resolvable from PATH`
      : `git.bat: not resolvable from PATH (depot_tools git_cache.py requires it)`,
  );

  const git = resolveGitExecutable({ env, platform, spawn, exists });
  if (git === null) {
    throw new Error(
      'no working git.exe was found on PATH or in the Git for Windows install directories; ' +
        'gclient needs a git.bat shim pointing at a real git.exe, so the sync is stopped here ' +
        'instead of failing later inside depot_tools/git_cache.py',
    );
  }

  const directory = gitShimDirectory(dest);
  mkdirSync(directory, { recursive: true });
  const gitBat = path.join(directory, GIT_BAT_NAME);
  writeFileSync(gitBat, gitBatContents(git.path));
  log(`git.bat shim: ${gitBat} -> ${git.path} (${git.version})`);
  return {
    directory,
    gitBat,
    gitExecutable: git.path,
    version: git.version,
    alreadyResolvable,
  };
}

/**
 * Read-only description of the git/python/PATH environment a child process
 * will inherit. Never writes anything, never logs a secret: only PATH entries
 * whose text mentions git are reported.
 */
export function describeGitEnvironment({
  env = process.env,
  platform = process.platform,
  spawn = spawnSync,
  exists = existsSync,
} = {}) {
  const entries = pathEntries(env, platform);
  const git = resolveGitExecutable({ env, platform, spawn, exists });
  return {
    platform,
    git: git === null ? null : { path: git.path, version: git.version },
    gitBatResolvable:
      platform === 'win32'
        ? resolvesInPathEntries(GIT_BAT_NAME, entries, { exists })
        : null,
    python: executableVersion('python', { env, spawn }),
    gitPathEntries: entries.filter((entry) =>
      entry.toLowerCase().includes('git'),
    ),
  };
}
